### ISSUE TITLE
memory copy error when creating a tensor from local data

### ISSUE THREAD

**Issue by fengwang** [VeriSilicon/TIM-VX#377]
I experienced a segmentation fault when creating a tensor from an array. It seems the memory address is not collectedly passed to vsi_nn. 

related code where memory is passed:

<https://github.com/VeriSilicon/TIM-VX/blob/d108661a03a12a6ada53ad8cbf4d2686c257c9e5/src/tim/vx/tensor.cc#L82>

Example code snippet:

```cpp
extern std::shared_ptr<tim::vx::Graph> default_graph;
std::shared_ptr<tim::vx::Tensor> tsor = [=]()
{
    unsigned char const dat[4] = { 0x0, 0x0, 0x0, 0xff };
    tim::vx::ShapeType _shape( { 4, } );                                                                                                                                             
    tim::vx::Quantization _quant( tim::vx::QuantType::ASYMMETRIC, 1.003921568627451f, 0 );                                                                                           
    tim::vx::TensorSpec _spec( tim::vx::DataType::UINT8, _shape, tim::vx::TensorAttribute::CONSTANT, _quant );                                                                       
    return default_graph->CreateTensor( _spec, &dat );                                                                                    
}();
```

**Comment by fengwang** [comment]
From gdb dumped information below
```
#0  0x0000fffff6686c9c in vxoContext_IsValid () from /usr/lib/libOpenVX.so.1
#1  0x0000fffff66dcdd4 in vxCreateTensor2 () from /usr/lib/libOpenVX.so.1
#2  0x0000fffff7afeff4 in _init_tensor (graph=0xaaaaaade1420, tensor=0xaaaaaaddf840, data=0x0) at /home/root/old_root/feng/workspace/tengine/tengine-lite/source/device/tim-vx/src/tim/vx/internal/src/vsi_nn_tensor.c:435
#3  0x0000fffff7aff214 in _create_tensor (graph=0xaaaaaade1420, data=0x0, attr=0xfffffff6ec90) at /home/root/old_root/feng/workspace/tengine/tengine-lite/source/device/tim-vx/src/tim/vx/internal/src/vsi_nn_tensor.c:521
#4  0x0000fffff7aff280 in vsi_nn_CreateTensor (graph=0xaaaaaade1420, attr=0xfffffff6ec90) at /home/root/old_root/feng/workspace/tengine/tengine-lite/source/device/tim-vx/src/tim/vx/internal/src/vsi_nn_tensor.c:540
#5  0x0000fffff7af3b24 in _add_tensor (graph=0xaaaaaade1420, id=0, attr=0xfffffff6ec90, data=0x0) at /home/root/old_root/feng/workspace/tengine/tengine-lite/source/device/tim-vx/src/tim/vx/internal/src/vsi_nn_graph.c:958
#6  0x0000fffff7af3ba8 in vsi_nn_AddTensor (graph=0xaaaaaade1420, id=4294967294, attr=0xfffffff6ec90, data=0x0)
    at /home/root/old_root/feng/workspace/tengine/tengine-lite/source/device/tim-vx/src/tim/vx/internal/src/vsi_nn_graph.c:982
#7  0x0000fffff7c2f674 in tim::vx::TensorImpl::Init (this=0xaaaaaaddf740) at /home/root/old_root/feng/workspace/tengine/tengine-lite/source/device/tim-vx/src/tim/vx/tensor.cc:189
#8  0x0000fffff7c2f124 in tim::vx::TensorImpl::TensorImpl (this=0xaaaaaaddf740, graph=0xaaaaaade1330, spec=..., data=0xffffffffba98)
......
```
at `#8`, the local memory at `0xffffffffba98` is passed to `TensorImpl` constructor, then `Init()` is invoked in `#7`. However, it seems `Init()` invokes `vsi_nn_AddTensor` with data address changed to `0x0`.
